version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  discord: antonioned/discord@0.0.4

jobs:
  build:
    working_directory: ~/pillarwallet-nodejs-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet-nodejs-sdk/.npmrc
      - run:
            name: Set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Packages
          command: npm i
      - run:
          name: Install TypeScript packages globally
          command: sudo npm i -g typescript tsc ts-node
      - run:
          name: Compile TypeScript
          command: npm run compile
      - run:
          name: Webpack bundle SDK for Production
          command: npm run build-production
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n Oops! Since *$CIRCLE_JOB* has failed no tests can be run! :circleci-fail:"
          webhook: "${SLACK_WEBHOOK_URL}"
      - discord/status:
          fail_only: true
          failure_message: "Triggered by: **${CIRCLE_USERNAME}** \\n\\n Oops! Since **$CIRCLE_JOB** has failed no tests can be run!"
          webhook: "${DISCORD_WEBHOOK_URL}"

  tests:
    working_directory: ~/pillarwallet-nodejs-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet-nodejs-sdk/.npmrc
      - run:
          name: Set Registry
          command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Packages
          command: npm i
      - run:
          name: Test
          command: npm run test:unit
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n Oops! *$CIRCLE_JOB* have failed, please fix them! :circleci-fail:"
          webhook: "${SLACK_WEBHOOK_URL}"
      - discord/status:
          fail_only: true
          failure_message: "Triggered by: **${CIRCLE_USERNAME}** \\n\\n Oops! **$CIRCLE_JOB** have failed, please fix them!"
          webhook: "${DISCORD_WEBHOOK_URL}"

  publish:
    working_directory: ~/pillarwallet-nodejs-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet-nodejs-sdk/.npmrc
      - run:
          name: Set Registry
          command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Install Packages
          command: npm i
      - run:
          name: Install TypeScript packages globally
          command: sudo npm i -g typescript tsc ts-node
      - run:
          name: Compile TypeScript
          command: npm run compile
      - run:
          name: Webpack bundle SDK for Production
          command: npm run build-production
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Announce Publish
          command: |
            chmod +x .circleci/announcePublish.sh
            chmod +x .circleci/announceDiscord.sh
            .circleci/announcePublish.sh "Platform Core SDK" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"
            .circleci/announceDiscord.sh "Platform Core SDK" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n *$CIRCLE_JOB* failed, new package is not published. :circleci-fail:"
          webhook: "${SLACK_WEBHOOK_URL}"
      - discord/status:
          fail_only: true
          failure_message: "Triggered by: **${CIRCLE_USERNAME}** \\n\\n **$CIRCLE_JOB** failed, new package is not published."
          webhook: "${DISCORD_WEBHOOK_URL}"

workflows:
  version: 2.1
  build_test_and_deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - publish:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
