version: 2
jobs:
  build:
    working_directory: ~/pillar
    docker:
      - image: circleci/node:8.9.4
    steps:
      - run:
          name: Add NPM_TOKEN to .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - deploy:
          npm:
            tag: /v[0-9]+(\.[0-9]+)*/
              commands:
                - npm publish
                - git push --follow-tags